In [2]:
#-- EJERCICIO 1 --
import numpy as np, pandas as pd, seaborn as sns
from matplotlib import pyplot as plt
pd.options.display.max_rows = 500

In [3]:
#-- EJERCICIO 2A) --
data = pd.read_csv('dataset_housing.csv')
data.head(5)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [4]:
#-- EJERCICIO 2 B) --
data.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
Alley             object
LotShape          object
LandContour       object
Utilities         object
LotConfig         object
LandSlope         object
Neighborhood      object
Condition1        object
Condition2        object
BldgType          object
HouseStyle        object
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
RoofStyle         object
RoofMatl          object
Exterior1st       object
Exterior2nd       object
MasVnrType        object
MasVnrArea       float64
ExterQual         object
ExterCond         object
Foundation        object
BsmtQual          object
BsmtCond          object
BsmtExposure      object
BsmtFinType1      object
BsmtFinSF1         int64
BsmtFinType2      object
BsmtFinSF2         int64
BsmtUnfSF          int64
TotalBsmtSF        int64
Heating           object


In [5]:
#-- EJERCICIO 3 A) --
houses = len(data)
print(f'Las viviendas que hay en el conjunto de datos son {houses}')

Las viviendas que hay en el conjunto de datos son 1460


-- EJERCICIO 3 B --


Al ejecutar este código nos sale el número de valores nulos que supuestamente hay en cada columna. Pero hay que tener cuidado, ya que si miramos la documentación, el valor de algunas variables puede ser 'NA' haciendo referncia a 'NO _', pero pandas lo puede confundir con el valor 'NaN', lo cual complicaría el procesado de los datos. En el siguiente ejercicio trataremos este problema con más detalle.

In [6]:
data.isnull().sum()

Id                  0
MSSubClass          0
MSZoning            0
LotFrontage       259
LotArea             0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType        872
MasVnrArea          8
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinSF1          0
BsmtFinType2       38
BsmtFinSF2          0
BsmtUnfSF           0
TotalBsmtSF         0
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
1stFlrSF            0
2ndFlrSF            0
LowQualFin

-- EJERCICIO 4 --

2. MSSubClass

In [13]:
print('- MSSubClass:')

#Hallar los valores únicos
unique = data['MSSubClass'].unique()

print(f'Los valores únicos son: {unique}')

#Ver el tipo en el dataframe
tipo = data['MSSubClass'].dtype 

print(f'Las variables son numéricas discretas: {tipo}')
print('Cada número representa el tipo de vivienda que se está ofertando:')
#from tabulate import tabulate #para mostrar el valor de las variables
mssubclass = [[20, '1-STORY 1946 & NEWER ALL STYLES'],
        [30,'1-STORY 1945 & OLDER'],
        [40, '1-STORY W/FINISHED ATTIC ALL AGES'],
        [45, '1-1/2 STORY - UNFINISHED ALL AGES'],
        [50, '1-1/2 STORY FINISHED ALL AGES'],
        [60, '2-STORY 1946 & NEWER'],
        [70,'2-STORY 1945 & OLDER'],
        [75,'2-1/2 STORY ALL AGES'],
        [80,'SPLIT OR MULTI-LEVEL'],
        [85,'SPLIT FOYER'],
        [90,'DUPLEX - ALL STYLES AND AGES'],
       [120,'1-STORY PUD (Planned Unit Development) - 1946 & NEWER'],
       [150,'1-1/2 STORY PUD - ALL AGES'],
       [160,'2-STORY PUD - 1946 & NEWER'],
       [180,'PUD - MULTILEVEL - INCL SPLIT LEV/FOYER'],
       [190,'2 FAMILY CONVERSION - ALL STYLES AND AGES']]
#print(tabulate(mssubclass))

#Hallar los valores nulos
n = data['MSSubClass'].isnull().sum() 

print(f'No hay valores nulos: {n}')

#Obtenemos el valor máximo
max = data['MSSubClass'].describe().T[['max']] 

###ASI ES COMO LO HACE EL PROFE, HAY OTRA FORMA MÁS BONITA DE HACERLO
#Obtenemos el valor mínimo
min = data['MSSubClass'].describe().T[['min']] 

print(f'Los valores máximo y mínimo: \n{max}\n{min}')

#Sacamos los outliers a partir de esta función:
def is_outlier_IQR(df):
    Q1=df.quantile(0.25)
    Q3=df.quantile(0.75)
    IQR = Q3-Q1
    return (df<(Q1-1.5*IQR)) | (df>(Q3+1.5*IQR))
outliermss1 = data['MSSubClass'][is_outlier_IQR(data['MSSubClass'])]

#Hacemos unique para ver los valores exactos
outliermss2 = outliermss1.unique()

#Usamos len() para ver cuantos outliers hay en la columna
print(f'Los valores de los outliers son: {outliermss2}, y en total son {len(outliermss1)} ')

- MSSubClass:
Los valores únicos son: [ 60  20  70  50 190  45  90 120  30  85  80 160  75 180  40]
Las variables son numéricas discretas: int64
Cada número representa el tipo de vivienda que se está ofertando:
---  -----------------------------------------------------
 20  1-STORY 1946 & NEWER ALL STYLES
 30  1-STORY 1945 & OLDER
 40  1-STORY W/FINISHED ATTIC ALL AGES
 45  1-1/2 STORY - UNFINISHED ALL AGES
 50  1-1/2 STORY FINISHED ALL AGES
 60  2-STORY 1946 & NEWER
 70  2-STORY 1945 & OLDER
 75  2-1/2 STORY ALL AGES
 80  SPLIT OR MULTI-LEVEL
 85  SPLIT FOYER
 90  DUPLEX - ALL STYLES AND AGES
120  1-STORY PUD (Planned Unit Development) - 1946 & NEWER
150  1-1/2 STORY PUD - ALL AGES
160  2-STORY PUD - 1946 & NEWER
180  PUD - MULTILEVEL - INCL SPLIT LEV/FOYER
190  2 FAMILY CONVERSION - ALL STYLES AND AGES
---  -----------------------------------------------------
No hay valores nulos: 0
Los valores máximo y mínimo: 
max    190.0
Name: MSSubClass, dtype: float64
min    20.0
Name: MSSubCl

No vamos a eliminar la columna MSSubClass porque no hay valores nulos, y a la hora de analizar los outliers, hemos visto que es mejor no eliminarlos ni reemplazarlos ya que el número que acompaña al tipo de vivienda está estrechamente relacionado con la calidad de está; siendo los valores 160, 180 y 190 de las viviendas más caras. Al ser mejores que el resto, es normal que no haya tantas viviendas así. Por estos motivos no vamos a eliminar ni modificar MSSubClass.

4. LotFrontage

In [34]:
print('- LotFrontage:')

#Hallar los valores únicos
unique = data['LotFrontage'].unique()

print(f'Los valores únicos son: {unique}')

#Ver el tipo en el dataframe
tipo = data['LotFrontage'].dtype 

print(f'Las variables son numéricas continuas: {tipo} \nRepresenta los pies de porción de suelo conectada a la propieda')

#Hallar los valores nulos
n = data['LotFrontage'].isnull().sum()

print(f'Los valores nulos son: {n}')

#Obtenemos el valor máximo
max = data['LotFrontage'].describe().T[['max']] 

#Obtenemos el valor mínimo
min = data['LotFrontage'].describe().T[['min']]

print(f'Los valores máximo y mínimo: \n{max}\n{min}')

#Sacamos los outliers a partir de esta función:
def is_outlier_IQR(df):
    Q1=df.quantile(0.25)
    Q3=df.quantile(0.75)
    IQR = Q3-Q1
    return (df<(Q1-1.5*IQR)) | (df>(Q3+1.5*IQR))
outlierlot1 = data['LotFrontage'][is_outlier_IQR(data['LotFrontage'])]

#Hacemos unique para ver los valores exactos
outlierlot2 = outlierlot1.unique()

#Usamos len() para ver cuantos outliers hay en la columna
print(f'Los valores de los outliers son: {outlierlot2}, y en total son {len(outlierlot1)} ')

#ES IMPOSIBLE QUE A UNA CASA NO LE CORRESPONDA NINGUN TROZO DE CALLE ASI QUE VAMOS ASÍ QUE YO SUSTITUIRIA LOS VALORES POR LA MEDIA
data2 = data['LotFrontage'].fillna(data['LotFrontage'].mean())
data2.isnull().sum() #AHORA NO HAY VALORES NaN, pero los outliers cambian

- LotFrontage:
Los valores únicos son: [ 65.  80.  68.  60.  84.  85.  75.  nan  51.  50.  70.  91.  72.  66.
 101.  57.  44. 110.  98.  47. 108. 112.  74. 115.  61.  48.  33.  52.
 100.  24.  89.  63.  76.  81.  95.  69.  21.  32.  78. 121. 122.  40.
 105.  73.  77.  64.  94.  34.  90.  55.  88.  82.  71. 120. 107.  92.
 134.  62.  86. 141.  97.  54.  41.  79. 174.  99.  67.  83.  43. 103.
  93.  30. 129. 140.  35.  37. 118.  87. 116. 150. 111.  49.  96.  59.
  36.  56. 102.  58.  38. 109. 130.  53. 137.  45. 106. 104.  42.  39.
 144. 114. 128. 149. 313. 168. 182. 138. 160. 152. 124. 153.  46.]
Las variables son numéricas continuas: float64 
Representa los pies de porción de suelo conectada a la propieda
Los valores nulos son: 259
Los valores máximo y mínimo: 
max    313.0
Name: LotFrontage, dtype: float64
min    21.0
Name: LotFrontage, dtype: float64
Los valores de los outliers son: [112. 115.  24.  21. 121. 122. 120. 134. 141. 174. 129. 140. 118. 116.
 150. 130. 137. 144. 114. 128. 

0

- Creemos que aquí las variables son continuas porque al ser la medida en pies del fragmento de suelo conectada a la propieda y estar definidas como un float, pueden tomar todo tipo de valores en un cierto intervalo.
- AÑADIR SI ESTA BIEN LO DE LOS NaN
- YO NO LA ELIMINARÍA, ESTÁ RELACIONADA CON EL VALOR DE LA CAS

6. Street

In [39]:
print('- Street:')

#Hallar los valores únicos
unique = data['Street'].unique()

print(f'Los valores únicos son: {unique}')

#Ver el tipo en el dataframe
tipo = data['Street'].dtype 

print(f'Las variables son categóricas sin orden: {tipo} \nRepresenta el tipo de suelo que accede a la propiedad') #Cambiarlo a tipo numerico

#Hallar los valores nulos
n = data['Street'].isnull().sum() 

print(f'No hay valores nulos: {n}')

- Street:
Los valores únicos son: ['Pave' 'Grvl']
Las variables son categóticas sin orden: object 
Representa el tipo de suelo que accede a la propiedad
No hay valores nulos: 0


In [54]:
#VOY A CAMBIAR LOS VALORES CATEGORICOS A NUMERICOS BINARIOS CON LO DE DUMMIES
streetdummies = pd.get_dummies(data['Street'], dtype=int) #pone un 1 si está en esa fila
streetdummies
streetdummies[streetdummies.iloc[:] == 1].sum()

Grvl       6.0
Pave    1454.0
dtype: float64

8. LotShape

In [59]:
print('- LotShape:')

#Hallar los valores únicos
unique = data['LotShape'].unique()

print(f'Los valores únicos son: {unique}')

#Ver el tipo en el dataframe
tipo = data['LotShape'].dtype 

print(f'Las variables son categóricas sin orden: {tipo} \nRepresenta la forma general de la propiedad') #Cambiarlo a tipo numerico

#Hallar los valores nulos
n = data['LotShape'].isnull().sum() 

print(f'No hay valores nulos: {n}')

- LotShape:
Los valores únicos son: ['Reg' 'IR1' 'IR2' 'IR3']
Las variables son categóticas sin orden: object 
Representa la forma general de la propiedad
No hay valores nulos: 0


In [65]:
lotdummies = pd.get_dummies(data['LotShape'],) #pone un 1 si está en esa fila
lotdummies
lotdummies[lotdummies.iloc[:] == 1].sum() #nº de filas con 1 en esa categoría

IR1    484
IR2     41
IR3     10
Reg    925
dtype: object

10. Utilities

In [72]:
print('- Utilities:')

#Hallar los valores únicos
unique = data['Utilities'].unique()

print(f'Los valores únicos son: {unique}')

#Ver el tipo en el dataframe
tipo = data['Utilities'].dtype 

print(f'Las variables son categóricas sin orden: {tipo} \nRepresenta los servicios disponibles en la vivienda') #Cambiarlo a tipo numerico

#Hallar los valores nulos
n = data['Utilities'].isnull().sum() 

print(f'No hay valores nulos: {n}')

- Utilities:
Los valores únicos son: ['AllPub' 'NoSeWa']
Las variables son categóticas sin orden: object 
Representa los servicios disponibles en la vivienda
No hay valores nulos: 0


In [73]:
utidummies = pd.get_dummies(data['Utilities'],) #pone un 1 si está en esa fila
utidummies
utidummies[utidummies.iloc[:] == 1].sum() #nº de filas con 1 en esa categoría

AllPub    1459
NoSeWa       1
dtype: object

12. Neighborhood

In [78]:
print('- Neighborhood:')

#Hallar los valores únicos
unique = data['Neighborhood'].unique()

print(f'Los valores únicos son: {unique}')

#Ver el tipo en el dataframe
tipo = data['Neighborhood'].dtype 

print(f'Las variables son categóricas sin orden: {tipo} \nRepresenta las ubicaciones dentro de los límites de la ciudad de Ames') #Cambiarlo a tipo numerico

#Hallar los valores nulos
n = data['Neighborhood'].isnull().sum() 

print(f'No hay valores nulos: {n}')

- Neighborhood:
Los valores únicos son: ['CollgCr' 'Veenker' 'Crawfor' 'NoRidge' 'Mitchel' 'Somerst' 'NWAmes'
 'OldTown' 'BrkSide' 'Sawyer' 'NridgHt' 'NAmes' 'SawyerW' 'IDOTRR'
 'MeadowV' 'Edwards' 'Timber' 'Gilbert' 'StoneBr' 'ClearCr' 'NPkVill'
 'Blmngtn' 'BrDale' 'SWISU' 'Blueste']
Las variables son categóticas sin orden: object 
Representa las ubicaciones dentro de los límites de la ciudad de Ames
No hay valores nulos: 0


In [95]:
neidummies = pd.get_dummies(data['Neighborhood']) #pone un 1 si está en esa fila
neidummies
neidummies[neidummies.iloc[:] == 1].sum() #nº de filas con 1 en esa categoría

Blmngtn     17
Blueste      2
BrDale      16
BrkSide     58
ClearCr     28
CollgCr    150
Crawfor     51
Edwards    100
Gilbert     79
IDOTRR      37
MeadowV     17
Mitchel     49
NAmes      225
NPkVill      9
NWAmes      73
NoRidge     41
NridgHt     77
OldTown    113
SWISU       25
Sawyer      74
SawyerW     59
Somerst     86
StoneBr     25
Timber      38
Veenker     11
dtype: object

14. GarageCars, GarageArea, GarageQual, GarageCond, GarageType,
GarageYrBlt y GarageFinish

In [84]:
print('- GarageCars:')

#Hallar los valores únicos
unique = data['GarageCars'].unique()

print(f'Los valores únicos son: {unique}')

#Ver el tipo en el dataframe
tipo = data['GarageCars'].dtype 

print(f'Las variables son numéricas discretas: {tipo} \nRepresenta cuántos coches caben en el garaje') #Cambiarlo a tipo numerico

#Hallar los valores nulos
n = data['GarageCars'].isnull().sum() 

print(f'No hay valores nulos: {n}')

#Obtenemos el valor máximo
max = data['GarageCars'].describe().T[['max']] 

###ASI ES COMO LO HACE EL PROFE, HAY OTRA FORMA MÁS BONITA DE HACERLO
#Obtenemos el valor mínimo
min = data['GarageCars'].describe().T[['min']] 

print(f'Los valores máximo y mínimo: \n{max}\n{min}')

#Sacamos los outliers a partir de esta función:
def is_outlier_IQR(df):
    Q1=df.quantile(0.25)
    Q3=df.quantile(0.75)
    IQR = Q3-Q1
    return (df<(Q1-1.5*IQR)) | (df>(Q3+1.5*IQR))
outliergaca1 = data['GarageCars'][is_outlier_IQR(data['GarageCars'])]

#Hacemos unique para ver los valores exactos
outliergaca2 = outliergaca1.unique()

#Usamos len() para ver cuantos outliers hay en la columna
print(f'Los valor del outlier es: {int(outliergaca2)}, y en total son {len(outliergaca1)} ')

- GarageCars:
Los valores únicos son: [2 3 1 0 4]
Las variables son numéricas discretas: int64 
Representa cuántos coches caben en el garaje
No hay valores nulos: 0
Los valores máximo y mínimo: 
max    4.0
Name: GarageCars, dtype: float64
min    0.0
Name: GarageCars, dtype: float64
Los valor del outlier es: 4, y en total son 5 


In [87]:
print('- GarageArea:')

#Hallar los valores únicos
unique = data['GarageArea'].unique()

print(f'Los valores únicos son: {unique}')

#Ver el tipo en el dataframe
tipo = data['GarageArea'].dtype 

print(f'Las variables son numéricas continua: {tipo} \nRepresenta el tamaño del garaje en pies cuadrados') #Cambiarlo a tipo numerico

#Hallar los valores nulos
n = data['GarageArea'].isnull().sum() 

print(f'No hay valores nulos: {n}') #SI NO TIENE GARAJE SALE 0

#Obtenemos el valor máximo
max = data['GarageArea'].describe().T[['max']] 

#Obtenemos el valor mínimo
min = data['GarageArea'].describe().T[['min']] 

print(f'Los valores máximo y mínimo: \n{max}\n{min}')

#Sacamos los outliers a partir de esta función:
def is_outlier_IQR(df):
    Q1=df.quantile(0.25)
    Q3=df.quantile(0.75)
    IQR = Q3-Q1
    return (df<(Q1-1.5*IQR)) | (df>(Q3+1.5*IQR))
outliergaa1 = data['GarageArea'][is_outlier_IQR(data['GarageArea'])]

#Hacemos unique para ver los valores exactos
outliergaa2 = outliergaa1.unique()

#Usamos len() para ver cuantos outliers hay en la columna
print(f'Los valores de los outliers son: {outliergaa2}, y en total son {len(outliergaa1)} ')

- GarageArea:
Los valores únicos son: [ 548  460  608  642  836  480  636  484  468  205  384  736  352  840
  576  516  294  853  280  534  572  270  890  772  319  240  250  271
  447  556  691  672  498  246    0  440  308  504  300  670  826  386
  388  528  894  565  641  288  645  852  558  220  667  360  427  490
  379  297  283  509  405  758  461  400  462  420  432  506  684  472
  366  476  410  740  648  273  546  325  792  450  180  430  594  390
  540  264  530  435  453  750  487  624  471  318  766  660  470  720
  577  380  434  866  495  564  312  625  680  678  726  532  216  303
  789  511  616  521  451 1166  252  497  682  666  786  795  856  473
  398  500  349  454  644  299  210  431  438  675  968  721  336  810
  494  457  818  463  604  389  538  520  309  429  673  884  868  492
  413  924 1053  439  671  338  573  732  505  575  626  898  529  685
  281  539  418  588  282  375  683  843  552  870  888  746  708  513
 1025  656  872  292  441  189  880  67

YO NO QUITABA LOS OUTLIERS AQUI, PORQUE PUEDE SER UNA CASA MUY GRANDE
SÍ ELIMINABA GarageCars PORQUE AMBOS INDICAN EL TAMAÑO, PERO GarageArea ES MÁS PRECISO

In [93]:
print('- GarageQual:')

#Hallar los valores únicos
unique = data['GarageQual'].unique()

print(f'Los valores únicos son: {unique}')

#Ver el tipo en el dataframe
tipo = data['GarageQual'].dtype 

print(f'Las variables son categóricas con orden: {tipo} \nRepresenta la calidad del garaje') 

#Hallar los valores nulos
n = data['GarageQual'].isnull().sum() 

print(f'Los valores nulos son: {n}') 

- GarageQual:
Los valores únicos son: ['TA' 'Fa' 'Gd' nan 'Ex' 'Po']
Las variables son categóricas con orden: object 
Representa la calidad del garaje
No hay valores nulos: 81


Aquí nos encontramos con el problema descrito en el ejercicio 3. Al mirar la documentación vemos que 'nan' se está confundiendo con 'NA', que significa 'NO GARAGE'. Por tanto vamos a cambiarlo.

In [92]:
new_GarageQual = data['GarageQual'].fillna('NG') #ESTA EN EL NOTEBOOK DEL PROFE

#Veamos ahora si hay valores nulos:
n = new_GarageQual.isnull().sum() 

print(f'No hay valores nulos: {n}')


No hay valores nulos: 0


In [102]:
#convertimos la variable categorica
gaquadummies = pd.get_dummies(new_GarageQual)#ponemos el que no tiene valores nulos
new_data = pd.merge(data, gaquadummies, left_index = True, right_index = True)
new_data[new_data.iloc[:] == 1].sum().tail(6)

Ex       3
Fa      48
Gd      14
NG      81
Po       3
TA    1311
dtype: object

In [103]:
print('- GarageCond:')

#Hallar los valores únicos
unique = data['GarageCond'].unique()

print(f'Los valores únicos son: {unique}')

#Ver el tipo en el dataframe
tipo = data['GarageCond'].dtype 

print(f'Las variables son categóricas con orden: {tipo} \nRepresenta la condición del garaje') 

#Hallar los valores nulos
n = data['GarageCond'].isnull().sum() 

print(f'Los valores nulos son: {n}') 

#ES LITERALMENTE IGUAL QUE LA ANTERIOR, YO LA ELIMINABA

- GarageCond:
Los valores únicos son: ['TA' 'Fa' nan 'Gd' 'Po' 'Ex']
Las variables son categóricas con orden: object 
Representa la calidad del garaje
No hay valores nulos: 81


In [104]:
print('- GarageType:')

#Hallar los valores únicos
unique = data['GarageType'].unique()

print(f'Los valores únicos son: {unique}')

#Ver el tipo en el dataframe
tipo = data['GarageType'].dtype 

print(f'Las variables son categóricas sin orden: {tipo} \nRepresenta la ubicación del garaje en la vivienda') 

#Hallar los valores nulos
n = data['GarageType'].isnull().sum() 

print(f'Los valores nulos son: {n}') 

- GarageType:
Los valores únicos son: ['Attchd' 'Detchd' 'BuiltIn' 'CarPort' nan 'Basment' '2Types']
Las variables son categóricas con orden: object 
Representa la condición del garaje
No hay valores nulos: 81


In [106]:
#mismo problema con el na
new_GarageType = data['GarageType'].fillna('NG') #ESTA EN EL NOTEBOOK DEL PROFE

#Veamos ahora si hay valores nulos:
gt = new_GarageType.isnull().sum() 

print(f'No hay valores nulos: {gt}')

#convertimos la variable categorica
gatydummies = pd.get_dummies(new_GarageType)#ponemos el que no tiene valores nulos
new_data = pd.merge(data, gatydummies, left_index = True, right_index = True)
new_data[new_data.iloc[:] == 1].sum().tail(7)

No hay valores nulos: 0


2Types       6
Attchd     870
Basment     19
BuiltIn     88
CarPort      9
Detchd     387
NG          81
dtype: object

In [109]:
print('- GarageYrBlt:')

#Hallar los valores únicos
unique = data['GarageYrBlt'].unique()

print(f'Los valores únicos son: {unique}')

#Ver el tipo en el dataframe
tipo = data['GarageYrBlt'].dtype 

print(f'Las variables son numéricas discretas: {tipo} \nRepresenta el año en el que se construyó el garaje') 

#Hallar los valores nulos
n = data['GarageYrBlt'].isnull().sum() 

print(f'Los valores nulos son: {n}')

#Obtenemos el valor máximo
max = data['GarageYrBlt'].describe().T[['max']] 

#Obtenemos el valor mínimo
min = data['GarageYrBlt'].describe().T[['min']] 

print(f'Los valores máximo y mínimo: \n{max}\n{min}')

#Sacamos los outliers a partir de esta función:
def is_outlier_IQR(df):
    Q1=df.quantile(0.25)
    Q3=df.quantile(0.75)
    IQR = Q3-Q1
    return (df<(Q1-1.5*IQR)) | (df>(Q3+1.5*IQR))
outliergay1 = data['GarageYrBlt'][is_outlier_IQR(data['GarageYrBlt'])]

#Hacemos unique para ver los valores exactos
outliergay2 = outliergay1.unique()

#Usamos len() para ver cuantos outliers hay en la columna
print(f'No hay outliers: {len(outliergay1)} ')

- GarageYrBlt:
Los valores únicos son: [2003. 1976. 2001. 1998. 2000. 1993. 2004. 1973. 1931. 1939. 1965. 2005.
 1962. 2006. 1960. 1991. 1970. 1967. 1958. 1930. 2002. 1968. 2007. 2008.
 1957. 1920. 1966. 1959. 1995. 1954. 1953.   nan 1983. 1977. 1997. 1985.
 1963. 1981. 1964. 1999. 1935. 1990. 1945. 1987. 1989. 1915. 1956. 1948.
 1974. 2009. 1950. 1961. 1921. 1900. 1979. 1951. 1969. 1936. 1975. 1971.
 1923. 1984. 1926. 1955. 1986. 1988. 1916. 1932. 1972. 1918. 1980. 1924.
 1996. 1940. 1949. 1994. 1910. 1978. 1982. 1992. 1925. 1941. 2010. 1927.
 1947. 1937. 1942. 1938. 1952. 1928. 1922. 1934. 1906. 1914. 1946. 1908.
 1929. 1933.]
Las variables son numéricas discretas: float64 
Representa el año en el que se construyó el garaje
Los valores nulos son: 81
Los valores máximo y mínimo: 
max    2010.0
Name: GarageYrBlt, dtype: float64
min    1900.0
Name: GarageYrBlt, dtype: float64
No hay outliers: 0 


In [117]:
#AQUÍ SI NOS FIJAMOS, EL Nº DE nan COINCIDE CON EL Nº DE NO GARAJES EN LAS COLUMNAS ANTERIORES, POR TANTO SIGNIFICA QUE NO TIENE GARAJE, YO LO SUSTITUIRÍA ASÍ:
new_GarageYear = data['GarageYrBlt'].fillna('NoGarage') #ESTA EN EL NOTEBOOK DEL PROFE

#Veamos ahora si hay valores nulos:
gt = new_GarageYear.isnull().sum()
new_GarageYear.unique()


array([2003.0, 1976.0, 2001.0, 1998.0, 2000.0, 1993.0, 2004.0, 1973.0,
       1931.0, 1939.0, 1965.0, 2005.0, 1962.0, 2006.0, 1960.0, 1991.0,
       1970.0, 1967.0, 1958.0, 1930.0, 2002.0, 1968.0, 2007.0, 2008.0,
       1957.0, 1920.0, 1966.0, 1959.0, 1995.0, 1954.0, 1953.0, 'NoGarage',
       1983.0, 1977.0, 1997.0, 1985.0, 1963.0, 1981.0, 1964.0, 1999.0,
       1935.0, 1990.0, 1945.0, 1987.0, 1989.0, 1915.0, 1956.0, 1948.0,
       1974.0, 2009.0, 1950.0, 1961.0, 1921.0, 1900.0, 1979.0, 1951.0,
       1969.0, 1936.0, 1975.0, 1971.0, 1923.0, 1984.0, 1926.0, 1955.0,
       1986.0, 1988.0, 1916.0, 1932.0, 1972.0, 1918.0, 1980.0, 1924.0,
       1996.0, 1940.0, 1949.0, 1994.0, 1910.0, 1978.0, 1982.0, 1992.0,
       1925.0, 1941.0, 2010.0, 1927.0, 1947.0, 1937.0, 1942.0, 1938.0,
       1952.0, 1928.0, 1922.0, 1934.0, 1906.0, 1914.0, 1946.0, 1908.0,
       1929.0, 1933.0], dtype=object)

In [119]:
print('- GarageFinish:')

#Hallar los valores únicos
unique = data['GarageFinish'].unique()

print(f'Los valores únicos son: {unique}')

#Ver el tipo en el dataframe
tipo = data['GarageFinish'].dtype 

print(f'Las variables son categóricas con orden: {tipo} \nRepresenta el acabado del garaje') 

#Hallar los valores nulos
n = data['GarageFinish'].isnull().sum() 

print(f'Los valores nulos son: {n}')

- GarageFinish:
Los valores únicos son: ['RFn' 'Unf' 'Fin' nan]
Las variables son categóricas con orden: object 
Representa la calidad del garaje
Los valores nulos son: 81


In [121]:
#mismo problema con el na
new_GarageF = data['GarageFinish'].fillna('NG') #ESTA EN EL NOTEBOOK DEL PROFE

#Veamos ahora si hay valores nulos:
gt = new_GarageF.isnull().sum() 

print(f'No hay valores nulos: {gt}')

#convertimos la variable categorica
gafidummies = pd.get_dummies(new_GarageF)#ponemos el que no tiene valores nulos
new_data = pd.merge(data, gafidummies, left_index = True, right_index = True)
new_data[new_data.iloc[:] == 1].sum().tail(4)

No hay valores nulos: 0


Fin    352
NG      81
RFn    422
Unf    605
dtype: object

16. OverallCond

In [122]:
print('- OverallCond:')

#Hallar los valores únicos
unique = data['OverallCond'].unique()

print(f'Los valores únicos son: {unique}')

#Ver el tipo en el dataframe
tipo = data['OverallCond'].dtype 

print(f'Las variables son numéricas discretas: {tipo} \nRepresenta la condición total de la casa') 

#Hallar los valores nulos
n = data['OverallCond'].isnull().sum() 

print(f'Los valores nulos son: {n}')

#Obtenemos el valor máximo
max = data['OverallCond'].describe().T[['max']] 

#Obtenemos el valor mínimo
min = data['OverallCond'].describe().T[['min']] 

print(f'Los valores máximo y mínimo: \n{max}\n{min}')

#Sacamos los outliers a partir de esta función:
def is_outlier_IQR(df):
    Q1=df.quantile(0.25)
    Q3=df.quantile(0.75)
    IQR = Q3-Q1
    return (df<(Q1-1.5*IQR)) | (df>(Q3+1.5*IQR))
outliercon1 = data['OverallCond'][is_outlier_IQR(data['OverallCond'])]

#Hacemos unique para ver los valores exactos
outliercon2 = outliercon1.unique()

#Usamos len() para ver cuantos outliers hay en la columna
print(f'Los valores de los outliers son: {outliercon2}, y en total son {len(outliercon1)} ')

- OverallCond:
Los valores únicos son: [5 8 6 7 4 2 3 9 1]
Las variables son numéricas discretas: int64 
Representa la condición total de la casa
Los valores nulos son: 0
Los valores máximo y mínimo: 
max    9.0
Name: OverallCond, dtype: float64
min    1.0
Name: OverallCond, dtype: float64
Los valores de los outliers son: [8 2 3 9 1], y en total son 125 
